package WeatherPrediction.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_CelsiusTemperature = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_FahrenheitTemperature = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_PredictionList = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Temperature = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Time = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_WeatherData = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_WeatherTimedData = new ConceptPresentationBuilder().create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.CelsiusTemperature:
        return props_CelsiusTemperature;
      case LanguageConceptSwitch.FahrenheitTemperature:
        return props_FahrenheitTemperature;
      case LanguageConceptSwitch.PredictionList:
        return props_PredictionList;
      case LanguageConceptSwitch.Temperature:
        return props_Temperature;
      case LanguageConceptSwitch.Time:
        return props_Time;
      case LanguageConceptSwitch.WeatherData:
        return props_WeatherData;
      case LanguageConceptSwitch.WeatherTimedData:
        return props_WeatherTimedData;
    }
    return null;
  }
}
