package WeatherPrediction.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int CelsiusTemperature = 0;
  public static final int FahrenheitTemperature = 1;
  public static final int PredictionList = 2;
  public static final int Temperature = 3;
  public static final int Time = 4;
  public static final int WeatherData = 5;
  public static final int WeatherTimedData = 6;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x9b3f871085384257L, 0xb16537afd7f0af97L);
    builder.put(0x77669cff9a1358fbL, CelsiusTemperature);
    builder.put(0x77669cff9a1358c4L, FahrenheitTemperature);
    builder.put(0x643ca018276d3e40L, PredictionList);
    builder.put(0x77669cff9a1691c8L, Temperature);
    builder.put(0x77669cff9a136175L, Time);
    builder.put(0x77669cff9a10e908L, WeatherData);
    builder.put(0x77669cff9a1358fdL, WeatherTimedData);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
